import type { MetadataRoute } from 'next'
 
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://lovigin.com',
      lastModified: new Date(),
      changeFrequency: 'hourly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/contacts',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/services/web',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/blog',
      lastModified: new Date(),
      changeFrequency: 'hourly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/blog/3',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/blog/2',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },

    {
      url: 'https://lovigin.com/blog/4',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },

    {
      url: 'https://lovigin.com/blog/5',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio',
      lastModified: new Date(),
      changeFrequency: 'hourly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/irisprophoto',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/unifood',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/voroninsfamilyllc',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/annaloviagina',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/busmanager',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/learnsy',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/all-banks',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/portfolio/gift-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/products',
      lastModified: new Date(),
      changeFrequency: 'hourly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/products/all-banks',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/products/gohood',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/products/learnsy',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/privacy-policy',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/terms-of-service',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/cookie-policy',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
    {
      url: 'https://lovigin.com/gift-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
      images: ['https://lovigin.com/favicon.ico'],
    },
  ]
}